project_id = "buwhgxyutfwadazjswio"

[functions.generate-news-article]
verify_jwt = true

[functions.sitemap]
verify_jwt = false

[functions.import-bookmyshow-events]
verify_jwt = false

[functions.register-for-event]
verify_jwt = false
