project_id = "buwhgxyutfwadazjswio"

[functions.generate-news-article]
verify_jwt = true

[functions.sitemap]
verify_jwt = false

[functions.import-bookmyshow-events]
verify_jwt = false

[functions.register-for-event]
verify_jwt = false

[functions.seed-nightlife-article]
verify_jwt = false

[functions.seed-tata-sierra-article]
verify_jwt = false

[functions.seed-cars-data]
verify_jwt = false

[functions.scrape-bookmyshow-events]
verify_jwt = false

[functions.event-ssr]
verify_jwt = false

[functions.page-ssr]
verify_jwt = false
