
-- Seed comprehensive events data for Jaipur (Dec 2025 - Mar 2026)
INSERT INTO public.events (
  title, slug, description, short_description, category, tags,
  start_date, end_date, venue_name, venue_address, city, locality,
  is_free, ticket_price, max_tickets, cover_image,
  organizer_name, organizer_email, organizer_phone,
  meta_title, meta_description, status, is_featured
) VALUES

-- MUSIC & CONCERTS
(
  'AP Dhillon: One Of One Tour — Jaipur',
  'ap-dhillon-one-of-one-tour-jaipur-2025',
  E'Experience the electrifying energy of AP Dhillon live in Jaipur! The Brown Munde sensation brings his chart-topping hits and signature Punjabi-pop style to the Pink City. Known for explosive performances and crowd-favorite tracks like "Brown Munde," "Excuses," and "With You," AP Dhillon promises an unforgettable night of music and entertainment.\n\n**What to Expect:**\n- Live performance of all major hits\n- High-energy stage production with world-class sound & lighting\n- Special guest appearances\n- Merchandise stalls\n- Food & beverage zones\n\n**Event Highlights:**\n- Gates open at 4:30 PM\n- Show starts at 6:30 PM\n- VIP meet & greet packages available\n- Parking available on-site',
  'AP Dhillon brings his One Of One Tour to Jaipur with an electrifying live concert featuring all his chart-topping hits.',
  'music',
  ARRAY['ap-dhillon', 'concert', 'live-music', 'punjabi-pop', 'hip-hop', 'brown-munde', 'jaipur-concert', 'one-of-one-tour'],
  '2025-12-28 18:30:00+05:30',
  '2025-12-28 23:00:00+05:30',
  'Jaipur Exhibition & Convention Centre (JECC)',
  'Sitapura Industrial Area, Jaipur, Rajasthan 302022',
  'Jaipur', 'Sitapura',
  false, 2499.00, 15000,
  'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1200',
  'BookMyShow Live', 'events@bookmyshow.com', '+91-9876543210',
  'AP Dhillon Live in Jaipur 2025 | One Of One Tour | Book Tickets',
  'Book tickets for AP Dhillon One Of One Tour in Jaipur on Dec 28, 2025. Experience live performance of Brown Munde, Excuses & more hits at JECC.',
  'published', true
),

(
  'Sanam Live India Tour — Jaipur',
  'sanam-live-india-tour-jaipur-2025',
  E'India''s most loved band SANAM is coming to Jaipur! Known for their soulful renditions of classic Bollywood songs and original compositions, Sanam has captured millions of hearts worldwide.\n\n**About SANAM:**\nWith over 10 million YouTube subscribers, SANAM is India''s most subscribed independent band. Their melodious covers of timeless classics and original tracks have made them a household name.\n\n**Concert Experience:**\n- Acoustic and band performances\n- Classic Bollywood covers\n- Original hits like "Gulabi Aankhen" and "Lag Ja Gale"\n- Intimate venue setting\n- Premium sound quality\n\n**Venue Facilities:**\n- Air-conditioned auditorium\n- Comfortable seating\n- Refreshments available\n- Ample parking space',
  'SANAM brings their magical live performance to Jaipur featuring soulful renditions of classic Bollywood songs and original hits.',
  'music',
  ARRAY['sanam', 'live-concert', 'bollywood-music', 'indie-band', 'romantic-songs', 'jaipur-events'],
  '2025-12-13 19:30:00+05:30',
  '2025-12-13 22:30:00+05:30',
  'Zee Studios',
  'Zee Studios, Jaipur, Rajasthan',
  'Jaipur', 'Malviya Nagar',
  false, 1299.00, 2000,
  'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200',
  'Zee Studios Events', 'events@zeestudios.com', '+91-9876543211',
  'Sanam Live Concert Jaipur 2025 | India Tour | Book Now',
  'Book tickets for Sanam Live India Tour in Jaipur on Dec 13, 2025. Experience their soulful Bollywood covers and original hits live.',
  'published', true
),

(
  'Jubin Nautiyal Live — Jaipur',
  'jubin-nautiyal-live-jaipur-2026',
  E'The golden voice of Bollywood, Jubin Nautiyal, is set to mesmerize Jaipur with his live concert! Known for blockbuster hits like "Tum Hi Aana," "Raataan Lambiyan," and "Manike," Jubin promises an evening of musical magic.\n\n**Concert Highlights:**\n- Live performance of all chartbusters\n- Unplugged acoustic segment\n- Fan interaction moments\n- State-of-the-art production\n- Special medley performances\n\n**Hit Songs You''ll Hear:**\n- Tum Hi Aana\n- Raataan Lambiyan\n- Lut Gaye\n- Manike\n- Bana Sharabi\n- And many more!\n\n**Event Details:**\n- Duration: 3+ hours\n- Multiple ticket categories\n- Early bird discounts available',
  'Jubin Nautiyal brings his melodious voice to Jaipur with a spectacular live concert featuring all his Bollywood chartbusters.',
  'music',
  ARRAY['jubin-nautiyal', 'bollywood-concert', 'live-music', 'tum-hi-aana', 'raataan-lambiyan', 'jaipur-concert-2026'],
  '2026-02-28 13:30:00+05:30',
  '2026-02-28 17:30:00+05:30',
  'JECC Jaipur',
  'Jaipur Exhibition & Convention Centre, Sitapura, Jaipur 302022',
  'Jaipur', 'Sitapura',
  false, 1999.00, 10000,
  'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=1200',
  'Live Nation India', 'tickets@livenation.in', '+91-9876543212',
  'Jubin Nautiyal Live Concert Jaipur 2026 | Book Tickets Online',
  'Book tickets for Jubin Nautiyal Live in Jaipur on Feb 28, 2026. Enjoy Tum Hi Aana, Raataan Lambiyan & more hits live at JECC.',
  'published', false
),

(
  'Sunidhi Chauhan — I Am Home India Tour',
  'sunidhi-chauhan-i-am-home-tour-jaipur-2026',
  E'The powerhouse vocalist Sunidhi Chauhan returns to her roots with the "I Am Home" India Tour! Experience the magic of her incredible vocal range and energy in this spectacular Valentine''s Day concert.\n\n**About the Tour:**\nSunidhi Chauhan, one of India''s most versatile playback singers, brings her iconic songs to life in this intimate tour celebrating her journey in Indian music.\n\n**Expected Setlist:**\n- Sheila Ki Jawani\n- Kamli\n- Dhoom Machale\n- Ainvayi Ainvayi\n- Crazy Kiya Re\n- Beedi\n- And 20+ more hits!\n\n**Valentine''s Special:**\n- Romantic song segment\n- Couple packages available\n- Rose ceremony for couples\n- Special dinner packages',
  'Sunidhi Chauhan performs live in Jaipur on Valentine''s Day as part of her I Am Home India Tour.',
  'music',
  ARRAY['sunidhi-chauhan', 'valentines-day-concert', 'bollywood-diva', 'live-performance', 'jaipur-valentines-2026'],
  '2026-02-14 19:00:00+05:30',
  '2026-02-14 23:00:00+05:30',
  'To Be Announced',
  'Jaipur, Rajasthan',
  'Jaipur', 'Central Jaipur',
  false, 2999.00, 8000,
  'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=1200',
  'District Events', 'info@district.in', '+91-9876543213',
  'Sunidhi Chauhan Live Jaipur 2026 | Valentines Day Concert',
  'Book tickets for Sunidhi Chauhan I Am Home Tour in Jaipur on Valentine''s Day Feb 14, 2026. A magical evening of Bollywood hits.',
  'published', true
),

-- COMEDY & STAND-UP
(
  'Daily Ka Kaam Hai — Aakash Gupta Stand-Up',
  'aakash-gupta-daily-ka-kaam-hai-jaipur',
  E'India''s favorite observational comedian Aakash Gupta brings his viral "Daily Ka Kaam Hai" tour to Jaipur! Known for his relatable middle-class humor and iconic catchphrases, Aakash promises an evening of non-stop laughter.\n\n**About Aakash Gupta:**\nWith over 3 million YouTube subscribers and billions of views, Aakash Gupta has become one of India''s most loved stand-up comedians. His observational humor about daily life resonates with audiences across the country.\n\n**Show Content:**\n- 90 minutes of fresh stand-up content\n- Stories from everyday Indian life\n- Audience interaction segments\n- Q&A session\n\n**Age Recommendation:** 16+\n**Language:** Hindi',
  'Aakash Gupta brings his hilarious "Daily Ka Kaam Hai" stand-up tour to Jaipur with fresh observational comedy.',
  'comedy',
  ARRAY['aakash-gupta', 'stand-up-comedy', 'daily-ka-kaam-hai', 'hindi-comedy', 'jaipur-comedy'],
  '2025-12-20 19:00:00+05:30',
  '2025-12-20 21:00:00+05:30',
  'Maharana Pratap Auditorium',
  'Maharana Pratap Auditorium, JLN Marg, Jaipur 302004',
  'Jaipur', 'JLN Marg',
  false, 999.00, 1500,
  'https://images.unsplash.com/photo-1527224538127-2104bb71c51b?w=1200',
  'BookMyShow Comedy', 'comedy@bookmyshow.com', '+91-9876543214',
  'Aakash Gupta Stand-Up Jaipur | Daily Ka Kaam Hai Tour',
  'Book tickets for Aakash Gupta Daily Ka Kaam Hai stand-up show in Jaipur. 90 minutes of hilarious observational comedy.',
  'published', true
),

(
  'VIR DAS — Mind Fool India Tour',
  'vir-das-mind-fool-tour-jaipur',
  E'Emmy-nominated comedian Vir Das brings his critically acclaimed tour to Jaipur! Fresh from his Netflix specials and international acclaim, Vir Das delivers sharp, intelligent humor that''s uniquely Indian yet globally relevant.\n\n**About Vir Das:**\nIndia''s biggest global comedy export, Vir Das has performed at prestigious venues worldwide including the Kennedy Center and London''s Royal Albert Hall. His Netflix specials have garnered millions of views globally.\n\n**Show Highlights:**\n- Brand new material\n- International touring content\n- Smart, thought-provoking comedy\n- Stories from global travels\n\n**Content Warning:** Adult humor, 18+\n**Duration:** 90 minutes',
  'Emmy-nominated Vir Das brings his Mind Fool Tour to Jaipur with sharp, globally-relevant comedy.',
  'comedy',
  ARRAY['vir-das', 'stand-up-comedy', 'netflix-comedian', 'mind-fool-tour', 'jaipur-comedy-show'],
  '2025-12-27 20:00:00+05:30',
  '2025-12-27 22:00:00+05:30',
  'Deep Smriti Auditorium',
  'Deep Smriti Auditorium, Jaipur, Rajasthan',
  'Jaipur', 'C-Scheme',
  false, 1499.00, 1200,
  'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=1200',
  'Weirdass Comedy', 'tickets@weirdasscomedy.com', '+91-9876543215',
  'Vir Das Live Jaipur 2025 | Mind Fool Tour | Book Tickets',
  'Book tickets for Vir Das Mind Fool Tour in Jaipur. Emmy-nominated comedian performs live with brand new material.',
  'published', true
),

(
  'Kisi Ko Batana Mat — Anubhav Singh Bassi',
  'anubhav-singh-bassi-kisi-ko-batana-mat-jaipur',
  E'The wait is over! India''s comedy sensation Anubhav Singh Bassi brings his legendary "Kisi Ko Batana Mat" show to Jaipur. Known for his viral videos and sold-out shows, Bassi''s storytelling comedy will leave you in splits!\n\n**Why Bassi is Special:**\n- Over 20 million YouTube subscribers\n- Every show sells out in minutes\n- Master storyteller with relatable humor\n- Clean comedy suitable for all ages\n\n**Show Experience:**\n- 2 hours of non-stop comedy\n- Stories from small-town India\n- Hilarious observations about everyday life\n- Interactive audience moments\n\n**Bassi''s Famous Bits:**\n- Hostel life stories\n- Family dynamics\n- Engineering college memories\n- Job interview disasters',
  'Anubhav Singh Bassi''s legendary "Kisi Ko Batana Mat" show comes to Jaipur with his signature storytelling comedy.',
  'comedy',
  ARRAY['anubhav-singh-bassi', 'bassi', 'stand-up-comedy', 'kisi-ko-batana-mat', 'jaipur-comedy', 'viral-comedian'],
  '2026-01-11 19:00:00+05:30',
  '2026-01-11 21:30:00+05:30',
  'Deep Smriti Auditorium',
  'Deep Smriti Auditorium, Jaipur, Rajasthan',
  'Jaipur', 'C-Scheme',
  false, 1299.00, 1200,
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200',
  'Only Much Louder', 'events@oml.in', '+91-9876543216',
  'Anubhav Singh Bassi Jaipur 2026 | Kisi Ko Batana Mat | Tickets',
  'Book tickets for Bassi''s Kisi Ko Batana Mat show in Jaipur. India''s most loved comedian performs his legendary set.',
  'published', true
),

(
  'Vipul Goyal — Unleashed Tour',
  'vipul-goyal-unleashed-tour-jaipur',
  E'Amazon Prime''s comedy star Vipul Goyal unleashes his brand new material in Jaipur! Known for his sharp wit and corporate humor, Vipul Goyal has been making India laugh for over a decade.\n\n**About Vipul Goyal:**\n- Pioneer of Hindi stand-up comedy\n- Amazon Prime special "Hai Taubba"\n- Corporate comedy expert\n- Relatable office humor\n\n**Tour Content:**\n- Fresh 2025 material\n- Corporate life observations\n- Marriage and relationship comedy\n- Current affairs commentary\n\n**Perfect For:**\n- Working professionals\n- Comedy enthusiasts\n- Corporate event follow-ups\n- Date nights',
  'Vipul Goyal unleashes his brand new comedy material in Jaipur with sharp corporate humor and witty observations.',
  'comedy',
  ARRAY['vipul-goyal', 'stand-up-comedy', 'corporate-comedy', 'amazon-prime', 'jaipur-comedy'],
  '2026-01-18 19:30:00+05:30',
  '2026-01-18 21:30:00+05:30',
  'Harishchandra Totuka Bhawan',
  'Harishchandra Totuka Bhawan, Jaipur, Rajasthan',
  'Jaipur', 'Raja Park',
  false, 799.00, 800,
  'https://images.unsplash.com/photo-1564585222527-c2777e03f703?w=1200',
  'Kommune India', 'events@kommuneindia.com', '+91-9876543217',
  'Vipul Goyal Unleashed Jaipur 2026 | Stand-Up Comedy Show',
  'Book tickets for Vipul Goyal Unleashed Tour in Jaipur. Sharp corporate humor and witty observations from the comedy veteran.',
  'published', false
),

(
  'Jaipur Comedy Festival 2025',
  'jaipur-comedy-festival-2025',
  E'The biggest comedy celebration in Rajasthan is here! Jaipur Comedy Festival brings together India''s finest comedians for a day of non-stop laughter.\n\n**Festival Lineup:**\n- 10+ comedians performing\n- Multiple stages and formats\n- Open mic opportunities\n- Comedy workshops\n- Meet and greet sessions\n\n**Event Features:**\n- Main stage performances\n- Intimate acoustic sets\n- Roast battles\n- Improv comedy\n- Regional comedy in Hindi & Rajasthani\n\n**Venue Amenities:**\n- 5-star hotel setting\n- Food and beverages\n- Networking lounge\n- Photo opportunities\n- Merchandise stalls',
  'Jaipur''s biggest comedy celebration featuring 10+ top comedians, workshops, and non-stop entertainment.',
  'comedy',
  ARRAY['jaipur-comedy-festival', 'comedy-fest', 'multiple-comedians', 'comedy-workshop', 'jaipur-events-2025'],
  '2025-12-13 14:00:00+05:30',
  '2025-12-13 23:00:00+05:30',
  'Hotel Clarks Amer',
  'Hotel Clarks Amer, JLN Marg, Jaipur 302017',
  'Jaipur', 'JLN Marg',
  false, 1999.00, 500,
  'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=1200',
  'Jaipur Comedy Club', 'fest@jaipurcomedyclub.com', '+91-9876543218',
  'Jaipur Comedy Festival 2025 | Biggest Comedy Event in Rajasthan',
  'Book tickets for Jaipur Comedy Festival 2025 at Hotel Clarks Amer. 10+ comedians, workshops, and a full day of laughter.',
  'published', true
),

(
  'PS — I Love You by Pranav Sharma',
  'ps-i-love-you-pranav-sharma-jaipur',
  E'Rising comedy star Pranav Sharma presents his brand new show "PS — I Love You" in Jaipur! A heartfelt and hilarious journey through relationships, life, and everything in between.\n\n**Show Theme:**\nA comedic exploration of modern relationships, dating disasters, and finding love in the digital age. Pranav combines storytelling with observational humor for a unique comedy experience.\n\n**What to Expect:**\n- 75 minutes of fresh content\n- Relationship comedy\n- Dating app disasters\n- Family expectations vs. reality\n- Modern love stories',
  'Pranav Sharma''s "PS — I Love You" explores modern relationships and dating disasters with hilarious storytelling.',
  'comedy',
  ARRAY['pranav-sharma', 'stand-up-comedy', 'relationship-comedy', 'dating-humor', 'jaipur-comedy'],
  '2025-12-21 18:00:00+05:30',
  '2025-12-21 19:30:00+05:30',
  'Taxila Auditorium',
  'Taxila Auditorium, Jaipur, Rajasthan',
  'Jaipur', 'Vaishali Nagar',
  false, 499.00, 400,
  'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1200',
  'AllEvents Comedy', 'comedy@allevents.in', '+91-9876543219',
  'PS I Love You Stand-Up Show Jaipur | Pranav Sharma Live',
  'Book tickets for Pranav Sharma''s PS I Love You comedy show in Jaipur. Fresh relationship comedy and dating disaster stories.',
  'published', false
),

(
  'Jaipur Open Mic Comedy Night',
  'jaipur-open-mic-comedy-night-dec-2025',
  E'Discover the next big comedian at Jaipur Open Mic Night! A platform for aspiring comedians to showcase their talent and for audiences to enjoy fresh, raw comedy.\n\n**Event Format:**\n- 15+ performers\n- 5-7 minutes each\n- Mix of experienced and new comics\n- Audience voting\n- Winner gets featured slot\n\n**Great For:**\n- Comedy enthusiasts\n- Aspiring comedians\n- Talent scouts\n- Anyone who loves to laugh\n\n**Venue Vibes:**\n- Intimate cafe setting\n- Craft beverages\n- Tapas menu\n- Cozy atmosphere',
  'Discover new comedy talent at Jaipur Open Mic Night featuring 15+ aspiring comedians and audience voting.',
  'comedy',
  ARRAY['open-mic', 'comedy-night', 'new-comedians', 'jaipur-nightlife', 'local-comedy'],
  '2025-12-28 20:00:00+05:30',
  '2025-12-28 23:00:00+05:30',
  'Gypsy Monkey',
  'Gypsy Monkey Cafe, C-Scheme, Jaipur',
  'Jaipur', 'C-Scheme',
  false, 299.00, 100,
  'https://images.unsplash.com/photo-1528495612343-9ca9f4a9f67c?w=1200',
  'Gypsy Monkey Events', 'events@gypsymonkey.in', '+91-9876543220',
  'Jaipur Open Mic Comedy Night Dec 2025 | Gypsy Monkey',
  'Book tickets for Jaipur Open Mic Comedy Night at Gypsy Monkey. Fresh comedy from 15+ performers with audience voting.',
  'published', false
),

(
  'Akshay Srivastava Live — Valentine Special',
  'akshay-srivastava-live-valentines-jaipur-2026',
  E'Celebrate Valentine''s Day with laughter! Comedy star Akshay Srivastava brings his hilarious take on love, relationships, and modern dating to Jaipur.\n\n**Valentine Special Content:**\n- Love in the time of social media\n- Arranged vs. love marriage debates\n- Couple problems decoded\n- First date disasters\n- In-laws survival guide\n\n**Perfect Date Night:**\n- Couple seating available\n- Complimentary welcome drink\n- Rose for every couple\n- Photo booth\n- Special dessert packages',
  'Celebrate Valentine''s Day with Akshay Srivastava''s hilarious take on love and relationships in Jaipur.',
  'comedy',
  ARRAY['akshay-srivastava', 'valentines-day-comedy', 'relationship-humor', 'date-night', 'jaipur-valentines'],
  '2026-02-14 20:00:00+05:30',
  '2026-02-14 22:00:00+05:30',
  'Strings Cocktail Lounge',
  'Strings Cocktail Lounge, Jaipur, Rajasthan',
  'Jaipur', 'C-Scheme',
  false, 799.00, 200,
  'https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=1200',
  'Strings Events', 'events@stringsjaipur.com', '+91-9876543221',
  'Akshay Srivastava Valentine Comedy Show Jaipur 2026',
  'Book tickets for Akshay Srivastava Valentine Special comedy show in Jaipur. Perfect date night with hilarious relationship comedy.',
  'published', false
),

(
  'Rajat Sood Live — India Tour',
  'rajat-sood-live-india-tour-jaipur',
  E'YouTube sensation Rajat Sood brings his viral comedy to Jaipur! Known for his unique style and relatable content, Rajat has amassed millions of followers with his hilarious takes on everyday life.\n\n**About Rajat Sood:**\n- 2M+ YouTube subscribers\n- Viral video creator\n- Unique observational style\n- Delhi boy humor\n\n**Show Highlights:**\n- YouTube video recreations\n- Live improvisation\n- Audience Q&A\n- Behind-the-scenes stories',
  'YouTube sensation Rajat Sood performs live in Jaipur with his unique observational comedy and viral humor.',
  'comedy',
  ARRAY['rajat-sood', 'youtube-comedian', 'stand-up-comedy', 'viral-comedy', 'jaipur-comedy'],
  '2026-01-25 20:00:00+05:30',
  '2026-01-25 22:00:00+05:30',
  'Strings Cocktail Lounge',
  'Strings Cocktail Lounge, Jaipur, Rajasthan',
  'Jaipur', 'C-Scheme',
  false, 699.00, 200,
  'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200',
  'Strings Events', 'events@stringsjaipur.com', '+91-9876543222',
  'Rajat Sood Live Jaipur 2026 | YouTube Comedian India Tour',
  'Book tickets for Rajat Sood Live in Jaipur. YouTube sensation performs his viral comedy material live on stage.',
  'published', false
),

-- FESTIVALS & CULTURAL EVENTS
(
  'SHIFT Festival 2025 — Jaipur',
  'shift-festival-2025-jaipur',
  E'SHIFT Festival returns to Jaipur for three days of creativity, culture, and innovation! India''s premier multi-disciplinary festival brings together art, music, technology, and wellness.\n\n**Festival Tracks:**\n🎨 **ART & DESIGN**\n- Art installations\n- Design exhibitions\n- Live art creation\n- Photography showcase\n\n🎵 **MUSIC & PERFORMANCE**\n- Live concerts\n- DJ sets\n- Dance performances\n- Theatre acts\n\n💡 **INNOVATION & TALKS**\n- TED-style talks\n- Startup showcase\n- Tech demonstrations\n- Panel discussions\n\n🧘 **WELLNESS & LIFESTYLE**\n- Yoga sessions\n- Meditation workshops\n- Healthy food zones\n- Sustainable living exhibits\n\n**Festival Pass Includes:**\n- Access to all three days\n- All stages and zones\n- Workshop participation\n- Festival merchandise\n- Food court access',
  'Three days of creativity, culture, and innovation at SHIFT Festival 2025 featuring art, music, tech, and wellness.',
  'festival',
  ARRAY['shift-festival', 'cultural-festival', 'art-music-festival', 'jaipur-festival-2025', 'multi-disciplinary', 'creative-festival'],
  '2025-12-19 10:00:00+05:30',
  '2025-12-21 22:00:00+05:30',
  'Birla Auditorium',
  'Birla Auditorium, Statue Circle, Jaipur 302001',
  'Jaipur', 'C-Scheme',
  false, 2499.00, 5000,
  'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=1200',
  'SHIFT Festival Foundation', 'info@shiftfestival.in', '+91-9876543223',
  'SHIFT Festival Jaipur 2025 | Art Music Culture Innovation',
  'Book passes for SHIFT Festival 2025 in Jaipur. 3 days of art, music, innovation, and wellness at Birla Auditorium.',
  'published', true
),

(
  'Tiger Festival at Jawahar Kala Kendra',
  'tiger-festival-jkk-jaipur-2025',
  E'Celebrate India''s national animal at the Tiger Festival! A two-day event dedicated to wildlife conservation, education, and appreciation of Rajasthan''s magnificent tigers.\n\n**Festival Highlights:**\n🐯 **EXHIBITIONS**\n- Tiger photography showcase\n- Wildlife art gallery\n- Conservation technology displays\n- Ranthambore documentation\n\n📚 **TALKS & PANELS**\n- Wildlife experts\n- Forest rangers\n- Conservation activists\n- Photographers\n\n👨‍👩‍👧‍👦 **FAMILY ACTIVITIES**\n- Kids'' wildlife workshop\n- Face painting\n- Nature trails\n- Documentary screenings\n\n🛍️ **MARKETPLACE**\n- Eco-friendly products\n- Wildlife merchandise\n- Tribal crafts\n- Organic food stalls',
  'Two-day wildlife conservation festival celebrating tigers with exhibitions, talks, and family activities at JKK.',
  'festival',
  ARRAY['tiger-festival', 'wildlife-conservation', 'jkk-jaipur', 'ranthambore', 'eco-festival', 'family-event'],
  '2025-12-13 09:00:00+05:30',
  '2025-12-14 18:00:00+05:30',
  'Jawahar Kala Kendra',
  'Jawahar Kala Kendra, JLN Marg, Jaipur 302004',
  'Jaipur', 'JLN Marg',
  true, 0, 2000,
  'https://images.unsplash.com/photo-1549366021-9f761d450615?w=1200',
  'Rajasthan Tourism & JKK', 'events@jkk.rajasthan.gov.in', '+91-9876543224',
  'Tiger Festival JKK Jaipur 2025 | Wildlife Conservation Event',
  'Attend the free Tiger Festival at JKK Jaipur on Dec 13-14, 2025. Wildlife exhibitions, expert talks, and family activities.',
  'published', true
),

(
  'Jaipur Jewellery Show (JJS) 2025',
  'jaipur-jewellery-show-jjs-2025',
  E'The world comes to Jaipur for JJS 2025 — Asia''s largest gems and jewellery trade show! Four days of exquisite craftsmanship, international business, and Rajasthani heritage.\n\n**Exhibition Highlights:**\n💎 **PRODUCT CATEGORIES**\n- Diamond jewellery\n- Kundan & Meenakari\n- Gold & silver ornaments\n- Gemstone collections\n- Costume jewellery\n- Watches & accessories\n\n🌍 **INTERNATIONAL DELEGATIONS**\n- Buyers from 50+ countries\n- B2B networking zones\n- Trade facilitation\n- Export promotion\n\n📚 **KNOWLEDGE SESSIONS**\n- Industry seminars\n- Design workshops\n- Trend forecasting\n- Certification programs\n\n**Visitor Categories:**\n- Trade professionals\n- Retail buyers\n- Designers\n- Investors',
  'Asia''s largest gems and jewellery trade show featuring international delegations, exhibitions, and industry seminars.',
  'business',
  ARRAY['jjs-2025', 'jewellery-show', 'gems-exhibition', 'trade-show', 'jaipur-jewellery', 'b2b-event'],
  '2025-12-19 10:00:00+05:30',
  '2025-12-22 19:00:00+05:30',
  'Jaipur Exhibition & Convention Centre',
  'JECC, Sitapura Industrial Area, Jaipur 302022',
  'Jaipur', 'Sitapura',
  false, 500.00, 50000,
  'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=1200',
  'Gem & Jewellery Export Promotion Council', 'jjs@gjepc.org', '+91-9876543225',
  'Jaipur Jewellery Show JJS 2025 | Asia Largest Gems Trade Show',
  'Register for JJS 2025 at JECC Jaipur. Asia''s largest jewellery trade show with 50+ country delegations.',
  'published', true
),

-- SPORTS EVENTS
(
  'Santosh Trophy — Group 1 Matches Jaipur',
  'santosh-trophy-group-1-jaipur-2025',
  E'Experience national football action in Jaipur! The prestigious Santosh Trophy brings Group 1 matches to the Pink City as state teams battle for glory.\n\n**Tournament Details:**\n⚽ **GROUP 1 TEAMS**\n- Rajasthan (Host)\n- Kerala\n- West Bengal\n- Goa\n- Maharashtra\n\n📅 **MATCH SCHEDULE**\n- Dec 17: Opening matches\n- Dec 18-20: Group stage\n- Dec 21: Final group matches\n\n🏟️ **VENUE FACILITIES**\n- 25,000 seating capacity\n- Food courts\n- Merchandise stalls\n- Kids'' zones\n\n**Why Attend:**\n- Witness future national players\n- Support Rajasthan team\n- Affordable family entertainment\n- Experience football culture',
  'National football championship matches at Jaipur with Rajasthan hosting Group 1 teams in Santosh Trophy.',
  'sports',
  ARRAY['santosh-trophy', 'football', 'national-championship', 'rajasthan-football', 'sports-event-jaipur'],
  '2025-12-17 15:00:00+05:30',
  '2025-12-21 21:00:00+05:30',
  'Vidhyadhar Nagar Stadium',
  'Vidhyadhar Nagar Stadium, Jaipur, Rajasthan',
  'Jaipur', 'Vidhyadhar Nagar',
  false, 100.00, 20000,
  'https://images.unsplash.com/photo-1553778263-73a83bab9b0c?w=1200',
  'All India Football Federation', 'santosh@aiff.com', '+91-9876543226',
  'Santosh Trophy Football Jaipur 2025 | Group 1 Matches Live',
  'Watch Santosh Trophy Group 1 football matches live in Jaipur Dec 17-21, 2025. Rajasthan hosts Kerala, Bengal & more.',
  'published', false
),

(
  'O.N. Dixit Memorial Badminton Championship',
  'on-dixit-memorial-badminton-jaipur-2025',
  E'The prestigious O.N. Dixit Memorial Badminton Championship returns to Jaipur! Six days of competitive badminton featuring district and veteran categories.\n\n**Tournament Categories:**\n🏸 **DISTRICT CHAMPIONSHIP**\n- Men''s singles & doubles\n- Women''s singles & doubles\n- Mixed doubles\n- Junior categories\n\n🏆 **VETERAN CATEGORIES**\n- 35+ age group\n- 45+ age group\n- 55+ age group\n- 65+ age group\n\n**Event Features:**\n- Trials for state selection\n- Cash prizes\n- Medals & trophies\n- Certificate of participation\n- Professional umpiring',
  'Six-day badminton championship featuring district and veteran categories with state selection trials.',
  'sports',
  ARRAY['badminton-championship', 'on-dixit-memorial', 'sports-jaipur', 'veteran-sports', 'district-championship'],
  '2025-12-23 08:00:00+05:30',
  '2025-12-28 20:00:00+05:30',
  'SMS Stadium Indoor Hall',
  'SMS Stadium Indoor Hall, Jaipur, Rajasthan',
  'Jaipur', 'SMS Stadium',
  false, 200.00, 1000,
  'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=1200',
  'Rajasthan Badminton Association', 'rba@badminton.in', '+91-9876543227',
  'O.N. Dixit Badminton Championship Jaipur 2025 | Register Now',
  'Register for O.N. Dixit Memorial Badminton Championship in Jaipur Dec 23-28. District & veteran categories with prizes.',
  'published', false
),

-- CULTURAL EXPERIENCES
(
  'Jaipur Evening Cooking & Cultural Experience',
  'jaipur-cooking-cultural-experience',
  E'Immerse yourself in authentic Rajasthani culture with this unique evening experience! Learn to cook traditional dishes, enjoy folk performances, and understand the rich heritage of Jaipur.\n\n**Experience Includes:**\n🍳 **COOKING SESSION**\n- Traditional Rajasthani recipes\n- Hands-on cooking class\n- Secret family recipes\n- Take-home recipe booklet\n\n💃 **CULTURAL PERFORMANCES**\n- Folk music (Manganiyar)\n- Ghoomar dance\n- Puppet show (Kathputli)\n- Storytelling session\n\n🏠 **HERITAGE SETTING**\n- Traditional haveli venue\n- Period furniture\n- Artisan demonstrations\n- Photo opportunities\n\n🍽️ **DINNER**\n- Authentic thali dinner\n- Dishes you prepared\n- Traditional sweets\n- Masala chai',
  'Authentic Rajasthani cooking class with folk performances and heritage dinner in a traditional haveli setting.',
  'cultural',
  ARRAY['cooking-class', 'cultural-experience', 'rajasthani-food', 'folk-music', 'heritage-tour', 'jaipur-experience'],
  '2025-12-14 17:00:00+05:30',
  '2025-12-14 21:00:00+05:30',
  'Heritage Haveli',
  'Traditional Haveli, Old City, Jaipur',
  'Jaipur', 'Old City',
  false, 2500.00, 20,
  'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=1200',
  'Jaipur Heritage Walks', 'book@jaipurwalks.com', '+91-9876543228',
  'Jaipur Cooking & Cultural Experience | Authentic Rajasthani Evening',
  'Book Jaipur Evening Cooking & Cultural Experience. Learn Rajasthani cooking, enjoy folk music, and dine in a heritage haveli.',
  'published', false
),

(
  'Magic Beans Creative Workshop for Kids',
  'magic-beans-kids-workshop-jaipur',
  E'Spark creativity in your little ones at Magic Beans Workshop! A fun-filled session designed to nurture imagination and artistic skills in children.\n\n**Workshop Activities:**\n🎨 **ART & CRAFT**\n- Painting sessions\n- Clay modeling\n- Paper crafts\n- Collage making\n\n🎭 **CREATIVE PLAY**\n- Drama games\n- Storytelling\n- Puppet making\n- Role play\n\n🔬 **DISCOVERY**\n- Science experiments\n- Nature exploration\n- Building blocks\n- Problem solving\n\n**Age Groups:**\n- 4-6 years\n- 7-10 years\n- 11-14 years\n\n**Includes:**\n- All materials\n- Healthy snacks\n- Take-home creations\n- Certificate',
  'Creative workshop for kids featuring art, craft, drama, and discovery activities in a fun, nurturing environment.',
  'kids',
  ARRAY['kids-workshop', 'creative-activities', 'art-craft', 'children-events', 'jaipur-kids'],
  '2025-12-15 10:00:00+05:30',
  '2025-12-15 13:00:00+05:30',
  'Magic Beans Studio',
  'Magic Beans Creative Studio, Vaishali Nagar, Jaipur',
  'Jaipur', 'Vaishali Nagar',
  false, 999.00, 30,
  'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=1200',
  'Magic Beans Education', 'hello@magicbeans.in', '+91-9876543229',
  'Magic Beans Kids Workshop Jaipur | Creative Activities for Children',
  'Book Magic Beans Creative Workshop for kids in Jaipur. Art, craft, drama, and discovery activities for ages 4-14.',
  'published', false
),

(
  'Late Night Comedy at Jaipur Comedy Club',
  'late-night-comedy-jaipur-club',
  E'Every weekend, Jaipur Comedy Club hosts the best late-night comedy in the city! Unwind after a long week with sharp, uncensored humor from top comedians.\n\n**Show Format:**\n- Host comedian\n- 3-4 featured acts\n- Headliner performance\n- Surprise guests\n\n**Late Night Vibes:**\n- Intimate 100-seat venue\n- Full bar service\n- Appetizer menu\n- 18+ content\n- Post-show hangouts\n\n**Regular Performers:**\n- Local Jaipur talent\n- Touring national acts\n- Open mic graduates\n- Rising stars',
  'Weekly late-night comedy shows featuring top comedians, full bar service, and intimate venue atmosphere.',
  'comedy',
  ARRAY['late-night-comedy', 'comedy-club', 'weekend-entertainment', 'jaipur-nightlife', 'stand-up'],
  '2025-12-20 22:00:00+05:30',
  '2025-12-21 00:30:00+05:30',
  'Jaipur Comedy Club',
  'Jaipur Comedy Club, C-Scheme, Jaipur',
  'Jaipur', 'C-Scheme',
  false, 599.00, 100,
  'https://images.unsplash.com/photo-1485178575877-1a13bf489dfe?w=1200',
  'Jaipur Comedy Club', 'shows@jaipurcomedyclub.com', '+91-9876543230',
  'Late Night Comedy Shows Jaipur | Weekend Entertainment',
  'Book late night comedy shows at Jaipur Comedy Club. Weekly weekend entertainment with top comedians and full bar.',
  'published', false
);
