// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbenryjgtbrjvqvxbigq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiZW5yeWpndGJyanZxdnhiaWdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU5Njc5NzQsImV4cCI6MjA5MTU0Mzk3NH0.-ExObEYUegSEjhQh2IfKXmOvw8cKT8h1ISXbAPnHgo0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Note: typed as `any` because the codebase references several tables/columns
// (coupons, reviews, community_posts, jaicoin_transactions, business_name, etc.)
// that aren't in the generated Database types yet. This unblocks the build
// without changing runtime behavior.
export const supabase: any = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});