name: Deploy Supabase Edge Functions

on:
  push:
    branches: [ "main" ]
    paths:
      - "supabase/functions/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase functions deploy sitemap --project-ref buwhgxyutfwadazjswio
          supabase functions deploy merchant-redirect --project-ref buwhgxyutfwadazjswio
          supabase functions deploy merchant-ssr --project-ref buwhgxyutfwadazjswio
          supabase functions deploy event-ssr --project-ref buwhgxyutfwadazjswio
          supabase functions deploy locality-ssr --project-ref buwhgxyutfwadazjswio
